### PR TITLE
Fixes for topology aware scheduling validation webhook

### LINKED ISSUE #325: Disabling TAS unintentionally disallows changes to existing `PodCliqueSet`s.
### What happened?

https://github.com/ai-dynamo/grove/pull/317#discussion_r2691539015

When TAS is disabled in the operator, any modifications made to existing PCS resources are being disallowed by the validating webhook. This unintentional behavior was introduced in #317.

### What did you expect to happen?

The behavior being observed is obviously not intended behavior, and modifications to PCS resources must be allowed after TAS is disabled.

New resources with `TopologyConstraint` should not be allowed to be created by the operator when TAS is disabled, but existing resources should be allowed to be updated/deleted.

### Environment

- Grove version 258e47c6fbb49cc9cf7e782311a7cf4869ac1aad

### PR DESCRIPTION
**Pull request by unmarshall**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When TAS is disabled then it validates the PCS to ensure that it does not have any TopologyConstraint set. This should only be done when a new PCS is created. Consider an existing PCS with TopologyConstraint set at one or more levels and it has been deployed when TAS was enabled. Now if the admin disabled TAS and restarts Grove, and if the PCS has some changes to its spec then validating webhook disallows it because it runs the validations to ensure that TopologyConstraints should not be defined for a PCS when TAS is disabled. While this is fine for newly create PCS it should not be skipped for PCS that is already running.

This PR fixes this behavior.

Additionally we also expose `ErrorMatcher` that was introduced in https://github.com/ai-dynamo/grove/pull/317 and use it in `webhook/admission/pcs/validation/podcliqueset_test.go` since the return type was changed for `pcsValidator.validate` to return `field.ErrorList`.

#### Which issue(s) this PR fixes:

Fixes #325 

#### Does this PR introduce a API change?

```release-note
NONE

```

#### Additional documentation e.g., enhancement proposals, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by renormalize — DISMISSED** [review]
thanks for addressing https://github.com/ai-dynamo/grove/pull/317#discussion_r2691539015.

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go [hunk 1]
```diff
@@ -192,9 +191,10 @@ func (v *pcsValidator) validatePodCliqueScalingGroupConfigs(fldPath *field.Path)
 	})
 	pclqScalingGroupNames := make([]string, 0, len(v.pcs.Spec.Template.PodCliqueScalingGroupConfigs))
 	var cliqueNamesAcrossAllScalingGroups []string
-	groupNameFiledPath := fldPath.Child("name")
 
-	for _, scalingGroupConfig := range v.pcs.Spec.Template.PodCliqueScalingGroupConfigs {
+	for i, scalingGroupConfig := range v.pcs.Spec.Template.PodCliqueScalingGroupConfigs {
+		fldPath = fldPath.Index(i)
```
Comment (gflarity) [inline operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: Reassigning fldPath inside the loop causes the path to accumulate indices?

Iteration 0: podCliqueScalingGroups[0] ✓
Iteration 1: podCliqueScalingGroups[0][1] ✗
Iteration 2: podCliqueScalingGroups[0][1][2] ✗

When I believe you want:

podCliqueScalingGroups[0]
podCliqueScalingGroups[1]
podCliqueScalingGroups[2]

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go [hunk 2]
```diff
@@ -333,7 +333,8 @@ func (v *pcsValidator) validateScalingGroupPodCliqueNames(pcsgName string, allPc
 	}
 
 	// validate scaling group  PodClique pods names are valid.
-	for _, pclqName := range pclqNameInScalingGrp {
+	for i, pclqName := range pclqNameInScalingGrp {
+		fldPath = fldPath.Index(i)
```
Comment (gflarity) [inline operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: Also, same thing right here. Accumulating [i] as you iterate in the fldPath.

File: operator/internal/webhook/admission/pcs/validation/podcliqueset_test.go [hunk 3]
```diff
@@ -51,53 +47,58 @@ func TestResourceNamingValidation(t *testing.T) {
 			scalingGroups: []grovecorev1alpha1.PodCliqueScalingGroupConfig{
 				createScalingGroupConfig("workers", []string{"prefill", "decode"}),
```
Comment (gflarity) [inline operator/internal/webhook/admission/pcs/validation/podcliqueset_test.go:48]: Note,  we also need test cases with more than on ScalingGroupConfigs... that would have caught this. I'd suggest adding more than one PodCliqueScalingGroupConfig and PodCliqueTemplateSpec in some of the tests.

**Comment by gflarity** [comment]
Didn't request changes to keep things unblocked, but looks like there's a couple bugs in the validation code.

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go [hunk 4]
```diff
@@ -192,9 +191,10 @@ func (v *pcsValidator) validatePodCliqueScalingGroupConfigs(fldPath *field.Path)
 	})
 	pclqScalingGroupNames := make([]string, 0, len(v.pcs.Spec.Template.PodCliqueScalingGroupConfigs))
 	var cliqueNamesAcrossAllScalingGroups []string
-	groupNameFiledPath := fldPath.Child("name")
 
-	for _, scalingGroupConfig := range v.pcs.Spec.Template.PodCliqueScalingGroupConfigs {
+	for i, scalingGroupConfig := range v.pcs.Spec.Template.PodCliqueScalingGroupConfigs {
+		fldPath = fldPath.Index(i)
+		groupNameFiledPath := fldPath.Child("name")
```
Comment (sanjaychatterjee) [inline operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: nit: `groupNameFiledPath` -> `groupNameFieldPath`

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go (hunk 1 above)
Comment (unmarshall) [reply operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: fixed

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go (hunk 2 above)
Comment (unmarshall) [reply operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: fixed

File: operator/internal/webhook/admission/pcs/validation/podcliqueset_test.go (hunk 3 above)
Comment (unmarshall) [reply operator/internal/webhook/admission/pcs/validation/podcliqueset_test.go:48]: added multiple PCSG configs to a test

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go (hunk 4 above)
Comment (unmarshall) [reply operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: done, this line is removed

File: operator/internal/webhook/admission/pcs/validation/podcliqueset.go (hunk 1 above)
Comment (renormalize) [reply operator/internal/webhook/admission/pcs/validation/podcliqueset.go]: thanks for catching this. I made this mistake since I was in a hurry to get things working.
