### PR TITLE
Addition of a `deletionTimestamp` on a `Pod` should trigger a `PodClique` reconciliation

### LINKED ISSUE #434: PCLQ controller fails to replace terminating Pods on NotReady nodes due to missed reconcile
### What happened?

When a Node becomes `NotReady`, the Pods on it first transition to `NotReady` (triggering a reconcile where they aren't yet terminating), and later get deleted by the node controller (receiving a `deletionTimestamp`).
However, the PCLQ controller does not trigger a new reconcile when the `deletionTimestamp` is added. This causes the Pods to remain in a terminating state without being replaced, resulting in the actual replica count dropping below the expected count and affecting service availability.

### What did you expect to happen?

When Pods on a `NotReady` node are marked for deletion (receive a `deletionTimestamp`), the PCLQ controller should detect this change and trigger a reconciliation. It should then promptly create new replacement Pods to maintain the desired replica count and ensure service availability.

### Environment

- Kubernetes version
- Grove version
- Scheduler details
- Cloud provider or hardware configuration
- Tools that you are using Grove together with
- Anything else that is relevant

### PR DESCRIPTION
**Pull request by xulinfei1996**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
In our scenario, when a Node becomes NotReady, the following sequence of events occurs:
1. The Pods on that Node first transition to the NotReady state;
2. After a period of time, the node controller deletes these Pods, at which point the Pods are marked with a `deletionTimestamp`.
In the PCLQ controller, step 1 triggers a reconcile, but since the Pods are not yet marked with a `deletionTimestamp`, the controller does not recognize them as being in a terminating state. By step 2, although the Pods now have a `deletionTimestamp`, the PCLQ controller does not trigger another reconcile.

This results in: Pods that are in a terminating state, but the PCLQ controller does not create new Pods to replace them, thereby affecting service availability and the expected replica count.
This PR aims to fix this issue by ensuring that when Pods enter a terminating state, the PCLQ controller can promptly detect this and create new Pods to maintain the desired replica count.

#### Which issue(s) this PR fixes:

Fixes #434

#### Does this PR introduce a API change?

```release-note
NONE
```

#### Additional documentation e.g., enhancement proposals, usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: operator/internal/controller/podclique/register.go [hunk 1]
```diff
@@ -129,7 +129,8 @@ func hasPodStatusChanged(updateEvent event.UpdateEvent) bool {
 	return hasReadyConditionChanged(oldPod.Status.Conditions, newPod.Status.Conditions) ||
 		hasLastTerminationStateChanged(oldPod.Status.InitContainerStatuses, newPod.Status.InitContainerStatuses) ||
 		hasLastTerminationStateChanged(oldPod.Status.ContainerStatuses, newPod.Status.ContainerStatuses) ||
-		hasStartedAndReadyChangedForAnyContainer(oldPod.Status.ContainerStatuses, newPod.Status.ContainerStatuses)
+		hasStartedAndReadyChangedForAnyContainer(oldPod.Status.ContainerStatuses, newPod.Status.ContainerStatuses) ||
+		hasTerminationChanged(oldPod, newPod)
```
Comment (kangclzjc) [inline operator/internal/controller/podclique/register.go]: Should we only pass DeletionTimestamp in the function like other function `hasStartedAndReadyChangedForAnyContainer`

**Comment by kangclzjc** [comment]
Thanks @xulinfei1996 , very great finding.

File: operator/internal/controller/podclique/register_test.go [hunk 2]
```diff
@@ -20,10 +20,44 @@ import (
...
+					},
+				},
+				ObjectNew: &corev1.Pod{
+					ObjectMeta: metav1.ObjectMeta{
+						DeletionTimestamp: ptr.To(metav1.Now()),
+					},
+				},
+			},
+			want: true,
+		},
```
Comment (Ronkahn21) [inline operator/internal/controller/podclique/register_test.go]: Please add another  test senario where status of pod does not consider changed as well

**Comment by renormalize** [comment]
Reviewing this, please do not merge this yet.

File: operator/internal/controller/podclique/register.go [hunk 3]
```diff
@@ -129,7 +131,8 @@ func hasPodStatusChanged(updateEvent event.UpdateEvent) bool {
 	return hasReadyConditionChanged(oldPod.Status.Conditions, newPod.Status.Conditions) ||
 		hasLastTerminationStateChanged(oldPod.Status.InitContainerStatuses, newPod.Status.InitContainerStatuses) ||
 		hasLastTerminationStateChanged(oldPod.Status.ContainerStatuses, newPod.Status.ContainerStatuses) ||
-		hasStartedAndReadyChangedForAnyContainer(oldPod.Status.ContainerStatuses, newPod.Status.ContainerStatuses)
+		hasStartedAndReadyChangedForAnyContainer(oldPod.Status.ContainerStatuses, newPod.Status.ContainerStatuses) ||
+		hasTerminationChanged(oldPod.DeletionTimestamp, newPod.DeletionTimestamp)
```
Comment (renormalize) [inline operator/internal/controller/podclique/register.go]: `hasPodStatusChanged()` only deals with changes in the `Status` field of the Pod.

The `DeletionTimestamp` is a metadata field, so I'd like to separate this and keep it outside of `hasPodStatusChanged()`. We can rename `hasTerminationChanged()` to `isMarkedForDeletion()` or something of that sort, and move the invocation into the `podPredicate()` function. There we can simply check something like:

```go
UpdateFunc: func(updateEvent event.UpdateEvent) bool {
		return isManagedPod(updateEvent.ObjectOld) && !hasPodSpecChanged(updateEvent) && (hasPodStatusChanged(updateEvent) || isMarkedForDeletion(updateEvent))
},
```

File: operator/internal/controller/podclique/register.go [hunk 4]
```diff
@@ -285,3 +288,7 @@ func isManagedPod(obj client.Object) bool {
 	}
 	return grovectrlutils.HasExpectedOwner(constants.KindPodClique, pod.OwnerReferences) && grovectrlutils.IsManagedByGrove(pod.GetLabels())
 }
+
+func hasTerminationChanged(oldDeletionTime, newDeletionTime *metav1.Time) bool {
+	return oldDeletionTime == nil && newDeletionTime != nil
+}
```
Comment (renormalize) [inline operator/internal/controller/podclique/register.go:318]: https://github.com/ai-dynamo/grove/pull/433/changes#r2827257745


```suggestion

func isMarkedForDeletion(oldDeletionTime, newDeletionTime *metav1.Time) bool {
	return oldDeletionTime == nil && newDeletionTime != nil
}
```

**Review by renormalize — CHANGES_REQUESTED** [review]
Thanks for the PR! Just a few nit comments.

The pods would eventually reach `.spec.replicas` in number after the `DELETE` event is sent, but for pods that are stuck in `Terminating` for long, the replacement pods might take a long time to be created if no event is generated for that specific PodClique.

Also, please fix the formatting through `GOWORK=off make check`, as the `check` CI job is failing.

File: operator/internal/controller/podclique/register.go (hunk 3 above)
Comment (xulinfei1996) [reply operator/internal/controller/podclique/register.go]: Done as  suggested: 
1. Separated `DeletionTimestamp` logic from `hasPodStatusChanged()
2. Renamed hasTerminationChanged() to isMarkedForDeletion()

File: operator/internal/controller/podclique/register_test.go (hunk 2 above)
Comment (xulinfei1996) [reply operator/internal/controller/podclique/register_test.go]: Done, renames the test as Test_isMarkedForDeletion()

File: operator/internal/controller/podclique/register.go (hunk 3 above)
Comment (renormalize) [reply operator/internal/controller/podclique/register.go]: thanks!

File: operator/internal/controller/podclique/register_test.go (hunk 2 above)
Comment (renormalize) [reply operator/internal/controller/podclique/register_test.go]: Added a couple more cases myself so we don't have to go through another review cycle. I hope that is fine.

(I also rebased on top of main since there were merge conflicts)

File: operator/internal/controller/podclique/register.go (hunk 1 above)
Comment (renormalize) [reply operator/internal/controller/podclique/register.go]: This was changed and is now outdated. Resolving this since all conversations need to be resolved to merge.
