### PR TITLE
Fix tas label

### LINKED ISSUE #379: TAS e2e test fai randomly
### What happened?

When do e2e test, sometimes node can be unready, then we will restart a new node. From log, I can see that it won't apply labels to the new node.

```2026-01-29T04:54:43.059Z	INFO	setup/k8s_clusters.go:776	WARN: 🚨 Found not ready node: k3d-shared-e2e-test-cluster-agent-1
2026-01-29T04:54:44.023Z	INFO	setup/k8s_clusters.go:783	WARN: ✅ Successfully replaced not ready node: k3d-shared-e2e-test-cluster-agent-1
2026-01-29T04:54:55.353Z	INFO	tests/topology_test.go:47	Get all pods once for verification
2026-01-29T04:54:55.359Z	INFO	tests/topology_test.go:390	3. Verify all 4 pods in same zone (PCS zone constraint)
topology_test.go:392: Failed to verify pods in same zone: node k3d-shared-e2e-test-cluster-agent-1 does not have topology label kubernetes.io/zone
```

### What did you expect to happen?

Replaced node should also have the label with the previous one

### Environment

- Kubernetes version
- Grove version
- Scheduler details
- Cloud provider or hardware configuration
- Tools that you are using Grove together with
- Anything else that is relevant

### PR DESCRIPTION
**Pull request by kangclzjc**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix TAS randomly failure
#### Which issue(s) this PR fixes:

Fixes #379 

#### Does this PR introduce a API change?

```release-note

```

#### Additional documentation e.g., enhancement proposals, usage docs, etc.:

```docs

```

### CODE REVIEW

File: operator/e2e/setup/k8s_clusters.go [hunk 1]
```diff
@@ -813,6 +818,30 @@ func replaceNotReadyNode(ctx context.Context, node *v1.Node, clientset *kubernet
...
+	}
+
+	if hasTopologyLabels {
+		logger.Debugf("🏷️  Reapplying topology labels to replaced node: %s", nodeName)
+		if err := reapplyTopologyLabelsToNode(ctx, clientset, nodeName, logger); err != nil {
+			// Log warning but don't fail - node is functional, just missing topology labels
+			logger.Warnf("⚠️  Failed to reapply topology labels to node %s: %v", nodeName, err)
+		}
+	}
+
```
Comment (Ronkahn21) [inline operator/e2e/setup/k8s_clusters.go]: Can you export this logic to sperate function

File: operator/e2e/setup/k8s_clusters.go [hunk 2]
```diff
@@ -813,6 +818,30 @@ func replaceNotReadyNode(ctx context.Context, node *v1.Node, clientset *kubernet
...
+		return fmt.Errorf("node %s did not rejoin cluster: %w", nodeName, err)
+	}
+
+	// Step 4: Reapply topology labels if they existed on the original node
+	// Check if this node had topology labels before replacement
+	hasTopologyLabels := false
+	for key := range originalLabels {
+		if key == TopologyLabelZone || key == TopologyLabelBlock || key == TopologyLabelRack {
+			hasTopologyLabels = true
+			break
```
Comment (Ronkahn21) [inline operator/e2e/setup/k8s_clusters.go]: We are adding topology labels to all of the nodes by default.As this does not effect to other test,.
so I think it safe to assume the topology labels are applied to any worker  (no need to check)

File: operator/e2e/setup/k8s_clusters.go [hunk 3]
```diff
@@ -1174,3 +1203,88 @@ func waitForWebhookReady(ctx context.Context, restConfig *rest.Config, logger *u
 		return true, nil
 	})
 }
+
+// waitForSingleNodeReady waits for a specific node to become ready after container restart
+func waitForSingleNodeReady(ctx context.Context, clientset *kubernetes.Clientset, nodeName string, timeout time.Duration, logger *utils.Logger) error {
```
Comment (Ronkahn21) [inline operator/e2e/setup/k8s_clusters.go]: Can you move this function under utils (e2e)

File: operator/e2e/setup/k8s_clusters.go [hunk 4]
```diff
@@ -1174,3 +1203,88 @@ func waitForWebhookReady(ctx context.Context, restConfig *rest.Config, logger *u
...
+				return nil
+			}
+
+			logger.Debugf("  Node %s found but not ready yet, waiting...", nodeName)
+		}
+	}
+}
+
+// reapplyTopologyLabelsToNode reapplies topology labels to a single node after replacement
+func reapplyTopologyLabelsToNode(ctx context.Context, clientset *kubernetes.Clientset, nodeName string, logger *utils.Logger) error {
```
Comment (Ronkahn21) [inline operator/e2e/setup/k8s_clusters.go]: As you save the original labels of the given node, can you simply reapply the topology once back to the new  Node

**Review by Ronkahn21 — CHANGES_REQUESTED** [review]
Good catch finding the edge case bug, I added a few comments

File: operator/e2e/setup/k8s_clusters.go (hunk 1 above)
Comment (kangclzjc) [reply operator/e2e/setup/k8s_clusters.go]: After remove hasTopolopy, this shouldn't be a problem

File: operator/e2e/setup/k8s_clusters.go (hunk 4 above)
Comment (kangclzjc) [reply operator/e2e/setup/k8s_clusters.go]: Yes, we could do that, let me do it.

File: operator/e2e/utils/k8s_client.go [hunk 5]
```diff
@@ -531,3 +531,45 @@ func scaleCRD(ctx context.Context, dynamicClient dynamic.Interface, gvr schema.G
 
 	return nil
 }
+
+// IsNodeReady checks if a node is in Ready state
+func IsNodeReady(node *v1.Node) bool {
```
Comment (unmarshall) [inline operator/e2e/utils/k8s_client.go]: It ideally does not belong here. The file is named `k8s_client.go` but in this method you are not really making any calls to the KAPI via the client. I would suggest that you create a new file under `utils` and call it `node.go` and move this there.

File: operator/e2e/utils/k8s_client.go [hunk 6]
```diff
@@ -531,3 +531,45 @@ func scaleCRD(ctx context.Context, dynamicClient dynamic.Interface, gvr schema.G
...
+	for _, condition := range node.Status.Conditions {
+		if condition.Type == v1.NodeReady {
+			return condition.Status == v1.ConditionTrue
+		}
+	}
+	return false // If no Ready condition is found, consider the node not ready
+}
+
+// WaitForSingleNodeReady waits for a specific node to become ready after container restart
+func WaitForSingleNodeReady(ctx context.Context, clientset *kubernetes.Clientset, nodeName string, timeout time.Duration, logger *Logger) error {
```
Comment (unmarshall) [inline operator/e2e/utils/k8s_client.go]: Also move this to `node.go`. Having one file `k8s_client.go` is a dumping place for all things to do with any k8s resource. Lets create more specific files. This has also been done already in `internal/utils/kubernetes`

File: operator/e2e/utils/k8s_client.go [hunk 7]
```diff
@@ -531,3 +531,45 @@ func scaleCRD(ctx context.Context, dynamicClient dynamic.Interface, gvr schema.G
...
+	const defaultPollInterval = 2 * time.Second
```
Comment (unmarshall) [inline operator/e2e/utils/k8s_client.go]: There is another function `isPodReady` - can you please remove that function and instead use `IsPodReady` as defined in `internal/utils/kubernetes/pod.go` to endure duplicate code? This is not really related to this PR but i am seeing this code for the first time. Did not get a chance to review it before. This is a small change.

File: operator/e2e/setup/k8s_clusters.go [hunk 8]
```diff
@@ -813,6 +804,18 @@ func replaceNotReadyNode(ctx context.Context, node *v1.Node, clientset *kubernet
 		return fmt.Errorf("failed to restart container for node %s: %w", nodeName, err)
 	}
 
+	// Step 3: Wait for the node to rejoin and become ready
+	logger.Debugf("⏳ Waiting for node to rejoin cluster: %s", nodeName)
```
Comment (unmarshall) [inline operator/e2e/setup/k8s_clusters.go]: should we wait for the node to be ready in order to re-apply the labels? The original code did not wait for node to be ready.

File: operator/e2e/utils/k8s_client.go [hunk 9]
```diff
@@ -531,3 +531,45 @@ func scaleCRD(ctx context.Context, dynamicClient dynamic.Interface, gvr schema.G
...
+
+	timeoutCtx, cancel := context.WithTimeout(ctx, timeout)
```
Comment (unmarshall) [inline operator/e2e/utils/k8s_client.go]: you can re-write this function and use an existing function `PollForCondition` instead.

```go
func WaitForNodeReady(ctx context.Context, logger *Logger, clientset *kubernetes.Clientset, nodeName string, timeout time.Duration) {
  return PollForCondition(ctx, timeout, defaultPollInterval, func() (bool, error) {
    node, err := clientset.CoreV1().Nodes().Get(ctx, nodeName, metav1.GetOptions{})
    if err != nil {
			// Node might not have rejoined yet (k3d agent still starting up)
			logger.Debugf("  Node %s not found yet (k3d agent still connecting), waiting...", nodeName)
			return false, nil
	}
    if IsNodeReady(node) {
			logger.Debugf("✅ Node %s has rejoined and is ready", nodeName)
			return true, nil
	}
    logger.Debugf("  Node %s found but not ready yet, waiting...", nodeName)
	return false, nil
  }
}
```

Alternatively you can rename this function to `WaitAndGetReadyNode` - since you are already making GET calls here there is no reason to make another GET call in `reapplyNodeLabels` which can simply be passed a ready `Node` object.

File: operator/e2e/setup/k8s_clusters.go (hunk 8 above)
Comment (kangclzjc) [reply operator/e2e/setup/k8s_clusters.go]: That's correct, actually we don't need wait for node to be ready and then apply the label. But since we replace a node, we should guarantee that new node should be Ready, otherwise, in next round check, this node may still be replaced ?

File: operator/e2e/utils/k8s_client.go (hunk 9 above)
Comment (kangclzjc) [reply operator/e2e/utils/k8s_client.go]: Yes, it will save one GET.

File: operator/e2e/utils/k8s_client.go (hunk 7 above)
Comment (kangclzjc) [reply operator/e2e/utils/k8s_client.go]: Done

File: operator/e2e/utils/k8s_client.go (hunk 6 above)
Comment (kangclzjc) [reply operator/e2e/utils/k8s_client.go]: That's a great idea. Learned a lot

**Review by unmarshall — APPROVED** [review]
